FROM python:3.8

WORKDIR /app

COPY requirements.txt .
COPY ./requirements-dev.txt .

RUN apt-get update && \
    apt-get install -yy libpq-dev build-essential && \
    pip install -r requirements.txt && \
    pip install -r requirements-dev.txt

COPY . /app
EXPOSE 5000